import os


AWS_REGION = os.environ.get("SAMPLE_AWS_REGION") or os.environ.get("AWS_REGION", "us-east-1")
BEDROCK_MODEL_ID = os.environ.get("BEDROCK_MODEL_ID", "us.anthropic.claude-opus-4-6-v1")
TABLE_NAME = os.environ.get("TABLE_NAME", "")
ARTIFACT_BUCKET = os.environ.get("ARTIFACT_BUCKET", "")
CONFIDENCE_THRESHOLD = float(os.environ.get("CONFIDENCE_THRESHOLD", "0.80"))
SUPPORTED_PRODUCTS = {"EQUITY"}
SUPPORTED_MARKETS = {"US"}
SUPPORTED_EXCEPTION_TYPES = {
    "SETTLEMENT_INSTRUCTION_MISMATCH",
    "ALLOCATION_MISMATCH",
    "COUNTERPARTY_PROFILE_MISMATCH",
    "SETTLEMENT_STATUS_MISMATCH",
    "MISSING_CONFIRMATION",
    "REFERENCE_DATA_STALE",
}
RESTRICTED_COUNTERPARTY_PREFIX = "CP-SYN-RESTRICTED"
NEAR_CUTOFF_MINUTES = 30
